name: dorm_meta
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.5

dependencies:
  glob: ^2.1.2
  path: ^1.9.0
  cider: ^0.2.8
  change: ^0.7.3
  rxdart: ^0.28.0
  logging: ^1.2.0

dev_dependencies:
  lints: ^4.0.0
