name: dorm_meta
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.5

dependencies:
  glob: ^2.1.2
  path: ^1.8.3
  cider: ^0.2.3
  change: ^0.7.1
  rxdart: ^0.27.7

dev_dependencies:
  lints: ^2.0.0
