name: example
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dorm:
    path: ../../dorm
  dorm_annotations:
    path: ../../dorm_annotations
  dorm_firebase_database:
    path: ../../dorm_firebase_database
  dorm_bloc_database:
    path: ../../dorm_bloc_database

  get_it: ^7.6.0
  decimal: ^2.3.2
  provider: ^6.0.5
  device_preview: ^1.1.0
  flutter_form_bloc: ^0.30.1
  intl: ^0.17.0
  flutter_spinbox: ^0.13.1

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.4.3
  dorm_generator:
    path: ../../dorm_generator

flutter:
  uses-material-design: true

dependency_overrides:
  dorm:
    path: ../../dorm
  dorm_annotations:
    path: ../../dorm_annotations
  dorm_bloc_database:
    path: ../../dorm_bloc_database
  dorm_generator:
    path: ../../dorm_generator
  intl: 0.17.0