name: dorm_example
description: A new Flutter package project.
version: 0.0.1

publish_to: none

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.1"

dependency_overrides:
  dorm_annotations:
    path: ..

dependencies:
  json_annotation: ^4.6.0
  dorm_annotations:
    path: ../../dorm_annotations

dev_dependencies:
  build_runner: ^2.2.0
  dorm_generator:
    path: ../../dorm_generator
  lints: ^2.0.0
