name: dorm_example
description: A new Flutter package project.
version: 0.0.1

publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.1"

dependency_overrides:
  dorm_framework:
    path: ../../dorm_framework
  dorm_annotations:
    path: ..
  dorm_generator:
    path: ../../dorm_generator

dependencies:
  json_annotation: ^4.6.0
  dorm_framework:
    path: ../../dorm_framework
  dorm_annotations:
    path: ../../dorm_annotations

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.7.1
  dorm_generator:
    path: ../../dorm_generator
  lints: ^2.0.0
