name: example
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dorm_framework:
    path: ../../dorm_framework
  dorm_annotations:
    path: ../../dorm_annotations
  dorm_firebase_database:
    path: ../../dorm_firebase_database
  dorm_bloc_database:
    path: ../../dorm_bloc_database

  intl: ^0.19.0
  get_it: ^7.7.0
  decimal: ^2.3.3
  provider: ^6.1.2
  device_preview: ^1.1.0
  flutter_spinbox: ^0.13.1
  flutter_form_bloc: ^0.31.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  dorm_generator:
    path: ../../dorm_generator

flutter:
  uses-material-design: true

dependency_overrides:
  dorm_framework:
    path: ../../dorm_framework
  dorm_annotations:
    path: ../../dorm_annotations
  dorm_bloc_database:
    path: ../../dorm_bloc_database
  dorm_generator:
    path: ../../dorm_generator
  uuid: 3.0.4
  intl: 0.19.0
  meta: 1.11.0
