import 'package:dorm_framework/dorm_framework.dart';
import 'package:dorm_memory_database/dorm_memory_database.dart';
import 'package:dorm_sync/dorm_sync.dart';
import 'package:test/test.dart';

class _NoteData {
  const _NoteData(this.text);

  final String text;
}

class _Note extends _NoteData {
  const _Note({required this.id, required String text}) : super(text);

  final String id;
}

class _StrongDependency extends Dependency<_NoteData> {
  const _StrongDependency() : super.strong();
}

class _NoteEntity
    implements
        Entity<_NoteData, _Note, String, SimpleCreation<_NoteData, String>> {
  const _NoteEntity();

  static const FieldSchema id = FieldSchema(fieldName: 'id', columnName: 'id');
  static const FieldSchema text = FieldSchema(
    fieldName: 'text',
    columnName: 'text',
  );
  static const EntitySchema entitySchema = EntitySchema(
    tableName: 'notes',
    primaryKeys: [id],
    fields: [text],
  );

  @override
  EntitySchema get schema => entitySchema;

  @override
  PrimaryKeyCodec<String> get primaryKeyCodec => const SinglePrimaryKeyCodec();

  @override
  IdentityGenerationStrategy get identityGeneration =>
      IdentityGenerationStrategy.engine;

  @override
  _Note fromData(ResolvedCreation<_NoteData, String> creation) =>
      _Note(id: creation.id, text: creation.data.text);

  @override
  _Note fromJson(String id, Map data) =>
      _Note(id: id, text: data['text'] as String);

  @override
  String identify(_Note model) => model.id;

  @override
  _Note convert(_Note model, _NoteData data) =>
      _Note(id: model.id, text: data.text);

  @override
  Map<String, Object?> toJson(_NoteData data) => {'text': data.text};
}

class _FailingPeekTarget
    extends EngineSyncTarget<Query<Object>, OffsetPageRequest> {
  _FailingPeekTarget(Engine engine) : super(engine, id: 'primary');

  @override
  Future<Model?> peek<Data, Model extends Data, I extends Object>(
    Entity<Data, Model, I, Creation<Data, I>> entity,
    I id,
  ) => throw StateError('primary unavailable');
}

class _FailingApplyTarget
    extends EngineSyncTarget<Query<Object>, OffsetPageRequest> {
  _FailingApplyTarget(this.shouldFail, Engine engine)
    : super(engine, id: 'replica');

  bool shouldFail;

  @override
  Future<void> apply<Data, Model extends Data, I extends Object>(
    Entity<Data, Model, I, Creation<Data, I>> entity,
    MutationChangeSet changeSet,
  ) {
    if (shouldFail) throw StateError('replica unavailable');
    return super.apply(entity, changeSet);
  }
}

class _RehydratingOutbox extends MemorySyncOutbox {
  @override
  Future<void> enqueue(SyncOperation operation) =>
      super.enqueue(SyncOperation.fromJson(operation.toJson()));
}

void main() {
  late Engine primary;
  late Engine replica;
  late MemorySyncOutbox outbox;
  late SynchronizedEngine<Query<Object>, OffsetPageRequest> engine;
  late BaseReference<Query<Object>, OffsetPageRequest> reference;
  const _NoteEntity entity = _NoteEntity();

  setUp(() {
    primary = Engine();
    replica = Engine();
    outbox = MemorySyncOutbox();
    engine = SynchronizedEngine<Query<Object>, OffsetPageRequest>(
      primary: EngineSyncTarget<Query<Object>, OffsetPageRequest>(
        primary,
        id: 'primary',
      ),
      replicas: [
        EngineSyncTarget<Query<Object>, OffsetPageRequest>(
          replica,
          id: 'replica',
        ),
      ],
      outbox: outbox,
      fallback: (_, _) => false,
    );
    reference = engine.createReference();
  });

  tearDown(() => outbox.close());

  test('replicates the final identity generated by the primary', () async {
    final _Note model = await reference.put(
      entity,
      Creation.explicit<_NoteData, String>(
        dependency: const _StrongDependency(),
        data: const _NoteData('first'),
        identity: 'note-1',
      ),
    );

    await engine.retry();
    final _Note? replicated = await replica.createReference().peek(
      entity,
      model.id,
    );

    expect(replicated?.id, 'note-1');
    expect(replicated?.text, 'first');
    expect(await outbox.pending(), isEmpty);
  });

  test('replicates bulk writes and identity-based deletions', () async {
    await reference.putAll(entity, [
      Creation.explicit<_NoteData, String>(
        dependency: const _StrongDependency(),
        data: const _NoteData('one'),
        identity: 'one',
      ),
      Creation.explicit<_NoteData, String>(
        dependency: const _StrongDependency(),
        data: const _NoteData('two'),
        identity: 'two',
      ),
    ]);
    await reference.pop(entity, 'one');
    await reference.popKeys(entity, ['two']);
    await reference.push(entity, const _Note(id: 'three', text: 'three'));
    await reference.purge(entity);
    await engine.flush();

    expect(
      await replica.createReference().peekAll(
        entity,
        const BaseFilter<Query<Object>>.empty(),
      ),
      isEmpty,
    );
  });
  test('uses the materialized patch and exact popAll identities', () async {
    await reference.pushAll(entity, [
      const _Note(id: 'a', text: 'keep'),
      const _Note(id: 'b', text: 'remove'),
    ]);
    await reference.patch(entity, 'a', (model) {
      final _Note current = model!;
      return _Note(id: current.id, text: 'updated');
    });
    await reference.popAll(
      entity,
      BaseFilter<Query<Object>>.value('remove', field: _NoteEntity.text),
    );

    await engine.retry();
    final List<_Note> models = await replica.createReference().peekAll(
      entity,
      const BaseFilter<Query<Object>>.empty(),
    );

    expect(models, hasLength(1));
    expect(models.single.id, 'a');
    expect(models.single.text, 'updated');
  });

  test(
    'falls back only when the policy classifies the primary error',
    () async {
      await replica.createReference().push(
        entity,
        const _Note(id: 'fallback', text: 'replica'),
      );
      final SynchronizedEngine<Query<Object>, OffsetPageRequest>
      fallbackEngine = SynchronizedEngine<Query<Object>, OffsetPageRequest>(
        primary: _FailingPeekTarget(primary),
        replicas: [
          EngineSyncTarget<Query<Object>, OffsetPageRequest>(
            replica,
            id: 'replica',
          ),
        ],
        outbox: MemorySyncOutbox(),
        fallback: (_, _) => true,
      );

      final _Note? result = await fallbackEngine.createReference().peek(
        entity,
        'fallback',
      );
      expect(result?.text, 'replica');
    },
  );

  test('keeps failed replica deliveries pending for retry', () async {
    final _FailingApplyTarget target = _FailingApplyTarget(true, replica);
    final MemorySyncOutbox retryOutbox = MemorySyncOutbox();
    final SynchronizedEngine<Query<Object>, OffsetPageRequest> retryEngine =
        SynchronizedEngine<Query<Object>, OffsetPageRequest>(
          primary: EngineSyncTarget<Query<Object>, OffsetPageRequest>(
            primary,
            id: 'primary',
          ),
          replicas: [target],
          outbox: retryOutbox,
          fallback: (_, _) => false,
        );

    await retryEngine.createReference().push(
      entity,
      const _Note(id: 'pending', text: 'retry'),
    );
    await retryEngine.retry();
    expect(await retryOutbox.pending(), isNotEmpty);

    target.shouldFail = false;
    await retryEngine.retry();
    expect(await retryOutbox.pending(), isEmpty);
    expect(
      (await replica.createReference().peek(entity, 'pending'))?.text,
      'retry',
    );
    await retryOutbox.close();
  });
  test('accepts a regular BaseEngine as a replica target', () async {
    final BaseEngine<Query<Object>, OffsetPageRequest> regularReplica = replica;
    final SynchronizedEngine<Query<Object>, OffsetPageRequest>
    plainReplicaEngine = SynchronizedEngine<Query<Object>, OffsetPageRequest>(
      primary: EngineSyncTarget<Query<Object>, OffsetPageRequest>(
        primary,
        id: 'primary',
      ),
      replicas: [
        EngineReplicaTarget<Query<Object>, OffsetPageRequest>(
          regularReplica,
          id: 'replica',
        ),
      ],
      outbox: MemorySyncOutbox(),
      fallback: (_, _) => false,
    );

    await plainReplicaEngine.createReference().push(
      entity,
      const _Note(id: 'plain', text: 'base engine'),
    );
    await plainReplicaEngine.flush();

    expect(
      (await replica.createReference().peek(entity, 'plain'))?.text,
      'base engine',
    );
    await plainReplicaEngine.close();
  });

  test('resolves an outbox operation after rehydration', () async {
    final _RehydratingOutbox rehydratingOutbox = _RehydratingOutbox();
    final SynchronizedEngine<Query<Object>, OffsetPageRequest>
    rehydratingEngine = SynchronizedEngine<Query<Object>, OffsetPageRequest>(
      primary: EngineSyncTarget<Query<Object>, OffsetPageRequest>(
        primary,
        id: 'primary',
      ),
      replicas: [
        EngineReplicaTarget<Query<Object>, OffsetPageRequest>(
          replica,
          id: 'replica',
        ),
      ],
      outbox: rehydratingOutbox,
      fallback: (_, _) => false,
      resolver: (_) =>
          (target, changeSet) => target.apply(entity, changeSet),
    );

    await rehydratingEngine.createReference().push(
      entity,
      const _Note(id: 'rehydrated', text: 'resolver'),
    );
    await rehydratingEngine.flush();

    expect(
      (await replica.createReference().peek(entity, 'rehydrated'))?.text,
      'resolver',
    );
    await rehydratingEngine.close();
  });
  test('serializes and rehydrates an operation without its callback', () {
    final MutationChangeSet changeSet = const MutationChangeSet(
      operationId: 'operation-1',
      sequence: 4,
      tableName: 'notes',
      kind: MutationKind.push,
      records: [
        MutationRecord(key: ['note-1'], data: {'text': 'serialized'}),
      ],
    );
    final SyncOperation operation = SyncOperation(
      changeSet: changeSet,
      replicaIds: const ['replica'],
      apply: (_, _) async {},
    );

    final SyncOperation rehydrated = SyncOperation.fromJson(operation.toJson());

    expect(rehydrated.changeSet.toJson(), changeSet.toJson());
    expect(rehydrated.replicaIds, ['replica']);
    expect(rehydrated.apply, isNull);
  });

  test('reports attempts and stack traces for failed delivery', () async {
    final _FailingApplyTarget target = _FailingApplyTarget(true, replica);
    final MemorySyncOutbox failureOutbox = MemorySyncOutbox();
    final SynchronizedEngine<Query<Object>, OffsetPageRequest> failureEngine =
        SynchronizedEngine<Query<Object>, OffsetPageRequest>(
          primary: EngineSyncTarget<Query<Object>, OffsetPageRequest>(
            primary,
            id: 'primary',
          ),
          replicas: [target],
          outbox: failureOutbox,
          fallback: (_, _) => false,
        );
    final Future<SyncFailure> failure = failureOutbox.failures.first;

    await failureEngine.createReference().push(
      entity,
      const _Note(id: 'failure', text: 'failure'),
    );
    await failureEngine.flush();

    final SyncFailure result = await failure;
    expect(result.delivery.attempts, 1);
    expect(result.delivery.lastStackTrace, isNotNull);
    expect(result.stackTrace.toString(), isNotEmpty);
    await failureOutbox.close();
  });

  test('does not expose distributed transactions', () {
    expect(
      engine,
      isNot(isA<TransactionalEngine<Query<Object>, OffsetPageRequest>>()),
    );
  });
  test('moves a delivery to dead letters at the configured limit', () async {
    final _FailingApplyTarget target = _FailingApplyTarget(true, replica);
    final MemorySyncOutbox deadLetterOutbox = MemorySyncOutbox();
    final SynchronizedEngine<Query<Object>, OffsetPageRequest>
    deadLetterEngine = SynchronizedEngine<Query<Object>, OffsetPageRequest>(
      primary: EngineSyncTarget<Query<Object>, OffsetPageRequest>(
        primary,
        id: 'primary',
      ),
      replicas: [target],
      outbox: deadLetterOutbox,
      fallback: (_, _) => false,
      maxAttempts: 1,
    );
    final Future<SyncFailure> failure = deadLetterOutbox.failures.first;

    await deadLetterEngine.createReference().push(
      entity,
      const _Note(id: 'dead-letter', text: 'terminal'),
    );
    await deadLetterEngine.flush();

    final SyncFailure result = await failure;
    expect(result.terminal, isTrue);
    expect(await deadLetterOutbox.pending(), isEmpty);
    expect(await deadLetterOutbox.deadLetters(), hasLength(1));
    await deadLetterOutbox.close();
  });
  test('replaying pending deliveries is idempotent', () async {
    await reference.push(entity, const _Note(id: 'same', text: 'before'));
    await engine.retry();
    await reference.push(entity, const _Note(id: 'same', text: 'after'));
    await engine.retry();
    await engine.retry();

    final _Note? replicated = await replica.createReference().peek(
      entity,
      'same',
    );
    expect(replicated?.text, 'after');
    expect(await outbox.pending(), isEmpty);
  });
}
