name: example
version: 0.1.0
publish_to: none
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  args: ^2.4.2
  dotenv: ^4.1.0
  mysql_client: ^0.0.27
  dorm_framework:
    path: ../../dorm_framework
  dorm_annotations:
    path: ../../dorm_annotations
  dorm_mysql_database:
    path: ../../dorm_mysql_database

dev_dependencies:
  lints: ^3.0.0
  build_runner: ^2.4.3
  json_serializable: ^6.7.1
  dorm_generator:
    path: ../../dorm_generator

dependency_overrides:
  meta: 1.12.0
  dorm_framework:
    path: ../../dorm_framework
  dorm_annotations:
    path: ../../dorm_annotations
  dorm_generator:
    path: ../../dorm_generator
