name: example
version: 0.1.0
publish_to: none
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  dorm_framework:
    path: ../../dorm_framework
  dorm_annotations:
    path: ../../dorm_annotations
  dorm_mysql_database:
    path: ../../dorm_mysql1_database
  mysql_client: ^0.0.27
  args: ^2.4.2

dev_dependencies:
  lints: ^2.0.1
  build_runner: ^2.4.3
  dorm_generator:
    path: ../../dorm_generator
  json_serializable: ^6.7.1

dependency_overrides:
  dorm_framework:
    path: ../../dorm_framework
  dorm_annotations:
    path: ../../dorm_annotations
  dorm_generator:
    path: ../../dorm_generator
