name: dorm_firestore_database_example
publish_to: none

environment:
  sdk: '>=3.11.5 <4.0.0'

dependencies:
  cloud_firestore: ^6.9.0
  dorm_annotations:
    path: ../../dorm_annotations
  dorm_framework:
    path: ../../dorm_framework
  dorm_firestore_database:
    path: ..
  firebase_core: ^4.14.0
  flutter:
    sdk: flutter
  json_annotation: ^4.12.0

dev_dependencies:
  build_runner: ^2.16.1
  dorm_generator:
    path: ../../dorm_generator
  lints: ^5.1.1

dependency_overrides:
  dorm_migrations:
    path: ../../dorm_migrations
  meta: 1.18.3
  dorm_annotations:
    path: ../../dorm_annotations
  dorm_framework:
    path: ../../dorm_framework
  dorm_generator:
    path: ../../dorm_generator
  dorm_firestore_database:
    path: ..
