name: dorm_annotations
version: 1.0.0-alpha.5
description: Exposes annotations used to generate code for dORM framework.
homepage: https://github.com/beet-software/dorm/tree/main/dorm_annotations
repository: https://github.com/beet-software/dorm.git
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  meta: ^1.16.0
  lints: ^5.0.0
  json_annotation: ^4.9.0
