name: dorm_annotations
version: 0.3.0
description: Provides annotations related with dORM code generation.
homepage: https://github.com/enzo-santos/dorm/tree/main/dorm_annotations
repository: https://github.com/enzo-santos/dorm.git
dependencies:
  meta: ^1.7.0
  lints: ^2.0.0
environment:
  sdk: ">=2.17.3 <3.0.0"
