name: dorm
description: Provides classes to implement the dORM framework.
version: 0.2.0

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  meta: ^1.7.0
  lints: ^2.0.0

dev_dependencies:
  build_runner: ^2.2.1
  mockito: ^5.3.2
  test: ^1.21.4
