name: dorm_bloc_database
version: 1.0.0-alpha.5
description: An implementation of a database engine for dORM using bloc and in-memory storage.
homepage: https://github.com/beet-software/dorm/tree/main/dorm_bloc_database
repository: https://github.com/beet-software/dorm.git
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  bloc: ^8.1.4
  uuid: ^4.5.1
  rxdart: ^0.28.0
  dorm_framework: ^1.0.0-alpha.3
dev_dependencies:
  lints: ^5.0.0

dependency_overrides:
  dorm_framework:
    path: ../dorm_framework
