name: dorm_bloc_database
version: 1.0.0-alpha.5
description: An implementation of a database engine for dORM using bloc and in-memory storage.
homepage: https://github.com/beet-software/dorm/tree/main/dorm_bloc_database
repository: https://github.com/beet-software/dorm.git
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  bloc: ^8.1.2
  uuid: ^3.0.7
  rxdart: ^0.27.7
  dorm_framework: ^1.0.0-alpha.3
dev_dependencies:
  lints: ^2.0.1

dependency_overrides:
  dorm_framework:
    path: ../dorm_framework
