name: dorm_framework
version: 1.0.0-alpha.4
description: Exposes classes, filters and joins to implement the dORM framework.
homepage: https://github.com/beet-software/dorm/tree/main/dorm
repository: https://github.com/beet-software/dorm.git
environment:
  sdk: '>=3.0.5 <4.0.0'
false_secrets:
  - example/lib/main.dart

dependencies:
  rxdart: ^0.27.7
dev_dependencies:
  test: ^1.24.3
  lints: ^2.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.5
