name: example
description: An application to demonstrate how to use dORM with BLoC.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dorm_framework:
    git:
      url: https://github.com/beet-software/dorm.git
      path: dorm_framework
      ref: main
  dorm_annotations:
    git:
      url: https://github.com/beet-software/dorm.git
      path: dorm_annotations
      ref: main
  dorm_bloc_database:
    git:
      url: https://github.com/beet-software/dorm.git
      path: dorm_bloc_database
      ref: main

  # The dependencies below are not required for dORM to work
  get_it: ^7.6.0
  device_preview: ^1.1.0
  provider: ^6.0.5

dev_dependencies:
  build_runner: ^2.4.3
  dorm_generator:
    git:
      url: https://github.com/beet-software/dorm.git
      path: dorm_generator
      ref: main

  # The dependencies below are not required for dORM to work
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

# This section should be removed in production
dependency_overrides:
  dorm_framework:
    path: ../../dorm_framework
  dorm_generator:
    path: ../../dorm_generator
  dorm_annotations:
    path: ../../dorm_annotations
  dorm_bloc_database:
    path: ..
