// dORM
// Copyright (C) 2023  Beet Software
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

import 'dependency.dart';

/// Describes how an identity should be obtained while creating a model.
sealed class IdentityRequest<I extends Object> {
  const IdentityRequest._();

  /// Requests the identity generated by the selected database engine.
  const factory IdentityRequest.auto() = AutoIdentity<I>;

  /// Supplies the final identity of the model.
  const factory IdentityRequest.explicit(I value) = ExplicitIdentity<I>;
}

/// Requests the identity generated by the selected database engine.
final class AutoIdentity<I extends Object> extends IdentityRequest<I> {
  const AutoIdentity() : super._();
}

/// Supplies the final identity of the model.
final class ExplicitIdentity<I extends Object> extends IdentityRequest<I> {
  /// Creates a request with an explicit identity.
  const ExplicitIdentity(this.value) : super._();

  /// The final identity to use for the model.
  final I value;
}

/// Describes the data and identity request used to create one model.
sealed class Creation<Data, I extends Object> {
  const Creation._({
    required this.dependency,
    required this.data,
    required this.identity,
  });

  /// Creates a request with an engine-generated identity.
  static AutoCreation<Data, I> auto<Data, I extends Object>({
    required Dependency<Data> dependency,
    required Data data,
  }) {
    return AutoCreation._(dependency: dependency, data: data);
  }

  /// Creates a request with an explicit identity.
  static ExplicitCreation<Data, I> explicit<Data, I extends Object>({
    required Dependency<Data> dependency,
    required Data data,
    required I identity,
  }) {
    return ExplicitCreation._(
      dependency: dependency,
      data: data,
      identity: identity,
    );
  }

  /// The dependency context used to construct the model.
  final Dependency<Data> dependency;

  /// The input data used to construct the model.
  final Data data;

  /// The requested identity behavior.
  final IdentityRequest<I> identity;
}

/// A creation request accepted by entities with a single primary key.
sealed class SimpleCreation<Data, I extends Object>
    extends Creation<Data, I> {
  const SimpleCreation._({
    required super.dependency,
    required super.data,
    required super.identity,
  }) : super._();
}

/// A creation request that delegates identity generation to an engine.
final class AutoCreation<Data, I extends Object>
    extends SimpleCreation<Data, I> {
  const AutoCreation._({
    required super.dependency,
    required super.data,
  }) : super._(identity: const AutoIdentity());
}

/// A creation request that supplies the final identity explicitly.
final class ExplicitCreation<Data, I extends Object>
    extends Creation<Data, I> {
  ExplicitCreation._({
    required super.dependency,
    required super.data,
    required I identity,
  }) : super._(identity: IdentityRequest.explicit(identity));
}

/// Contains a resolved identity and the inputs used to construct a model.
class ResolvedCreation<Data, I extends Object> {
  /// Creates a resolved creation context.
  const ResolvedCreation({
    required this.dependency,
    required this.data,
    required this.id,
    required this.wasGenerated,
  });

  /// The dependency context used to construct the model.
  final Dependency<Data> dependency;

  /// The input data used to construct the model.
  final Data data;

  /// The final identity assigned to the model.
  final I id;

  /// Whether the identity was generated by the engine.
  final bool wasGenerated;
}
