name: dorm_memory_database
description: A dORM's Reference implementation using Dart data types.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  uuid: ^3.0.6
  dorm:
    git:
      url: https://github.com/enzo-santos/dorm.git
      ref: main
      path: dorm

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
