// dORM
// Copyright (C) 2023  Beet Software
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

import 'dart:io';
import 'dart:isolate';

import 'package:mustache_template/mustache_template.dart';
import 'package:path/path.dart' as p;

import 'profile.dart';

/// Contains the generated project location and the commands needed to run it.
class GenerationResult {
  /// The engine profile used to create the project.
  final ExampleProfile profile;

  /// The absolute path of the generated project.
  final String path;

  /// The commands that should be run after generation.
  final List<String> instructions;

  /// Creates a generation result.
  const GenerationResult({
    required this.profile,
    required this.path,
    required this.instructions,
  });
}

/// Renders a complete dORM showcase project from the bundled templates.
class ExampleGenerator {
  /// Generates a project for [profile] in [output].
  ///
  /// The output directory must be empty or must not exist. [projectName] is
  /// used as the generated Dart package name.
  Future<GenerationResult> generate(
    ExampleProfile profile,
    Directory output, {
    required String projectName,
  }) async {
    if (projectName.isEmpty || !_validPackageName.hasMatch(projectName)) {
      throw ArgumentError.value(
        projectName,
        'projectName',
        'The output directory name must be a valid Dart package name.',
      );
    }

    if (output.existsSync() && output.listSync().isNotEmpty) {
      throw StateError('The output directory is not empty: ${output.path}');
    }
    await output.create(recursive: true);

    final Map<String, Object> context = {
      ...profile.toTemplateContext(projectName),
      'profile': profile.name,
      'flutter': profile.isFlutter,
      'dart': !profile.isFlutter,
      'project': projectName,
      ..._engineContext(profile),
      'auditIdDefinition': switch (profile.name) {
        'postgres' => 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
        'mysql' => 'INTEGER PRIMARY KEY AUTO_INCREMENT',
        'sqlite' => 'INTEGER PRIMARY KEY AUTOINCREMENT',
        _ => 'INTEGER PRIMARY KEY',
      },
    };

    for (final String templatePath in _templatePaths(profile)) {
      final String source = await _readTemplate(templatePath);
      final Template template = Template(source, name: templatePath);
      final String rendered = template.renderString(context);
      if (rendered.contains('{{')) {
        throw StateError('Unresolved template tag in $templatePath.');
      }
      final String relativeTemplatePath = templatePath
          .replaceFirst(RegExp(r'^templates/[^/]+/'), '')
          .replaceFirst('.mustache', '');
      final String publicTemplatePath = switch (relativeTemplatePath) {
        'gitignore' => '.gitignore',
        'env.example' => '.env.example',
        _ => relativeTemplatePath,
      };
      final String relativePath = publicTemplatePath == 'models.dart'
          ? 'lib/models.dart'
          : templatePath.startsWith('templates/sql/')
          ? p.join('sql', publicTemplatePath)
          : publicTemplatePath;
      final File file = File(p.join(output.path, relativePath));
      await file.parent.create(recursive: true);
      await file.writeAsString(rendered);
    }

    return GenerationResult(
      profile: profile,
      path: output.absolute.path,
      instructions: _instructions(profile, output.path),
    );
  }

  Map<String, Object> _engineContext(ExampleProfile profile) {
    return switch (profile.name) {
      'memory' => {
        'engineImport':
            "import 'package:dorm_memory_database/dorm_memory_database.dart';",
        'engineSetup': 'final Engine engine = Engine();',
        'engineClose': '',
        'engineQuery': 'Query',
      },
      'bloc' => {
        'engineImport':
            "import 'package:dorm_bloc_database/dorm_bloc_database.dart';",
        'engineSetup': 'final Engine engine = Engine();',
        'engineClose': '',
        'engineQuery': 'Query',
      },
      'firebase' => {
        'engineImport':
            "import 'package:dorm_firebase_database/dorm_firebase_database.dart';\nimport 'firebase_options.dart';",
        'engineSetup':
            "await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);\n  FirebaseDatabase.instance.useDatabaseEmulator('127.0.0.1', 9000);\n  final Engine engine = Engine(const FirebaseInstance(), path: 'dorm-example');",
        'engineClose': '',
        'engineQuery': 'Query',
      },
      'firestore' => {
        'engineImport':
            "import 'package:cloud_firestore/cloud_firestore.dart';\nimport 'package:firebase_core/firebase_core.dart';\nimport 'package:dorm_firestore_database/dorm_firestore_database.dart';\nimport 'firebase_options.dart';",
        'engineSetup':
            "await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);\n  FirebaseFirestore.instance.useFirestoreEmulator('127.0.0.1', 8080);\n  final Engine engine = Engine(FirebaseFirestore.instance);",
        'engineClose': '',
        'engineQuery': 'Query',
      },
      'http' => {
        'engineImport':
            "import 'package:http/http.dart' as http;\nimport 'package:dorm_http_database/dorm_http_database.dart';",
        'engineSetup':
            "final http.Client client = http.Client();\n  final Uri baseUri = Uri.parse(const String.fromEnvironment('HTTP_BASE_URI', defaultValue: 'http://localhost:8080/api/'));\n  final HttpMapping mapping = _createMapping();\n  final Engine engine = Engine(client: client, baseUri: baseUri, mapping: mapping);",
        'engineClose': 'client.close();',
        'engineQuery': 'Query',
      },
      'postgres' => {
        'engineImport':
            "import 'package:postgres/postgres.dart';\nimport 'package:dorm_postgres_database/dorm_postgres_database.dart';",
        'engineSetup':
            "final Connection connection = await Connection.open(Endpoint(host: _requiredEnvironment('POSTGRES_HOST'), port: int.parse(_requiredEnvironment('POSTGRES_PORT')), database: _requiredEnvironment('POSTGRES_DATABASE'), username: _requiredEnvironment('POSTGRES_USERNAME'), password: _requiredEnvironment('POSTGRES_PASSWORD')));\n  final Engine engine = Engine(connection);",
        'engineClose': 'await connection.close();',
        'engineQuery': 'Query',
      },
      'mysql' => {
        'engineImport':
            "import 'package:mysql_client/mysql_client.dart';\nimport 'package:dorm_mysql_database/dorm_mysql_database.dart';",
        'engineSetup':
            "final MySQLConnection connection = await MySQLConnection.createConnection(host: _requiredEnvironment('MYSQL_HOST'), port: int.parse(_requiredEnvironment('MYSQL_PORT')), databaseName: _requiredEnvironment('MYSQL_DATABASE'), userName: _requiredEnvironment('MYSQL_USERNAME'), password: _requiredEnvironment('MYSQL_PASSWORD'));\n  await connection.connect();\n  final Engine engine = Engine(connection);",
        'engineClose': 'await connection.close();',
        'engineQuery': 'Query',
      },
      'mongo' => {
        'engineImport':
            "import 'package:mongo_dart/mongo_dart.dart';\nimport 'package:dorm_mongo_database/dorm_mongo_database.dart';",
        'engineSetup':
            "final Db database = Db(_requiredEnvironment('MONGO_URI'));\n  await database.open();\n  final Engine engine = Engine(database);",
        'engineClose': 'await database.close();',
        'engineQuery': 'Query',
      },
      'sqlite' => {
        'engineImport':
            "import 'package:sqlite_async/sqlite_async.dart';\nimport 'package:dorm_sqlite_database/dorm_sqlite_database.dart';",
        'engineSetup':
            "final SqliteDatabase database = SqliteDatabase(path: 'store.sqlite');\n  final String schema = await File('sql/schema.sql').readAsString();\n  await database.executeMultiple(schema);\n  final Engine engine = Engine(database);",
        'engineClose': 'await database.close();',
        'engineQuery': 'Query',
      },
      _ => throw StateError('No context for ${profile.name}.'),
    };
  }

  List<String> _templatePaths(ExampleProfile profile) {
    final List<String> paths = [
      'templates/common/pubspec.yaml.mustache',
      'templates/common/analysis_options.yaml.mustache',
      'templates/common/gitignore.mustache',
      'templates/common/models.dart.mustache',
      'templates/common/README.md.mustache',
    ];
    if (profile.isFlutter) {
      paths.add('templates/flutter/lib/main.dart.mustache');
      paths.add('templates/flutter/web/index.html.mustache');
      if (profile.name == 'firebase' || profile.name == 'firestore') {
        paths.add('templates/flutter/lib/firebase_options.dart.mustache');
      }
    } else {
      paths.add('templates/dart/bin/main.dart.mustache');
    }
    if (profile.docker) {
      paths.add('templates/docker/docker-compose.yml.mustache');
      if (profile.requiresEnvironment) {
        paths.add('templates/docker/env.example.mustache');
      }
    }
    if (profile.httpServer) {
      paths.add('templates/http/server/pubspec.yaml.mustache');
      paths.add('templates/http/server/Dockerfile.mustache');
      paths.add('templates/http/server/bin/main.dart.mustache');
    }
    if (profile.name == 'postgres' ||
        profile.name == 'mysql' ||
        profile.name == 'sqlite') {
      paths.add('templates/sql/schema.sql.mustache');
    }
    return paths;
  }

  Future<String> _readTemplate(String packagePath) async {
    final Uri? uri = await Isolate.resolvePackageUri(
      Uri.parse('package:dorm_example/dorm_example.dart'),
    );
    if (uri == null || uri.scheme != 'file') {
      throw StateError('Could not resolve template $packagePath.');
    }
    final Directory packageRoot = File.fromUri(uri).parent.parent;
    return File(p.join(packageRoot.path, packagePath)).readAsString();
  }

  List<String> _instructions(ExampleProfile profile, String output) {
    final String cd = 'cd "${Directory(output).absolute.path}"';
    final List<String> result = [cd];
    if (profile.docker) result.add('docker compose up -d');
    result.add(profile.isFlutter ? 'flutter pub get' : 'dart pub get');
    result.add('dart run build_runner build');
    result.add(profile.isFlutter ? 'flutter run -d chrome' : 'dart analyze');
    if (!profile.isFlutter) result.add('dart run');
    return result;
  }
}

final RegExp _validPackageName = RegExp(r'^[a-z][a-z0-9_]*$');
