name: dorm_http_database
version: 1.0.0-alpha.5
resolution: workspace
description: An HTTP and JSON database engine for dORM.
homepage: https://github.com/beet-software/dorm/tree/main/dorm_http_database
repository: https://github.com/beet-software/dorm.git

environment:
  sdk: '>=3.11.5 <4.0.0'

dependencies:
  dorm_framework: ^2.0.0-dev.1
  http: ^1.6.0
  uuid: ^4.6.0

dev_dependencies:
  dorm_test: ^1.0.0-alpha.5
  lints: ^5.0.0
  test: ^1.32.0
