targets:
  $default:
    builders:
      generators|annotations:
        enabled: true

builders:
  generators:
    target: :lib
    import: package:dorm_generator/dorm_generator.dart
    auto_apply: dependents
    build_to: source
    applies_builders:
      - source_gen|combining_builder
      - json_serializable:json_serializable
    builder_factories:
      - generateOrm
    build_extensions:
      .dart:
        - .g.dart

  json_serializable:json_serializable:
    import: package:json_serializable/builder.dart
    auto_apply: dependents
    build_to: cache
    applies_builders:
      - source_gen|combining_builder
    builder_factories:
      - jsonSerializable
    build_extensions:
      .dart:
        - json_serializable.g.part
