builders:
  generators:
    target: :lib
    import: package:dorm_generator/dorm_generator.dart
    build_extensions:
      .dart:
        - .dorm.dart
    auto_apply: dependents
    build_to: source
    runs_before:
      - json_serializable|json_serializable
    builder_factories:
      - generateOrm
