name: dorm_generator
description: A new Flutter package project.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  build: ^2.3.0
  analyzer: ^5.3.1
  source_gen: ^1.2.2
  json_serializable: ^6.3.1
  
  dorm_annotations:
    git:
      url: https://github.com/enzo-santos/dorm.git
      ref: main
      path: dorm_annotations

dev_dependencies:
  lints: ^2.0.0
  build_runner: ^2.1.11
