name: dorm_generator
version: 1.0.0-alpha.5
description: Generates code to implement the dORM framework based on annotations.
homepage: https://github.com/beet-software/dorm/tree/main/dorm_generator
repository: https://github.com/beet-software/dorm.git
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  meta: ^1.16.0
  dartx: ^1.2.0
  build: ^2.4.1
  graphs: ^2.0.0
  analyzer: ^6.8.0
  source_gen: ^1.5.0
  dart_style: ^2.3.7
  code_builder: ^4.10.1
  json_serializable: ^6.8.0
  dorm_annotations: ^1.0.0-alpha.3
dev_dependencies:
  path: ^1.9.1
  test: ^1.25.8
  lints: ^3.0.0
  build_runner: ^2.4.13
  copy_with_extension_gen: ^5.0.4

dependency_overrides:
  dorm_annotations:
    path: ../dorm_annotations
