name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pkg: [dorm_framework, dorm_annotations, dorm_generator, dorm_firebase_database, dorm_bloc_database]
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Move into subdirectory
        run: cd ${{ matrix.pkg }}
      - name: Install dependencies
        run: dart pub get
      - name: Analyze project source
        run: dart analyze
