name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pkg: [dorm_framework, dorm_annotations]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      
      - name: Install dependencies
        working-directory: ./${{ matrix.pkg }}
        run: dart pub get

      - name: Build models
        if: ${{ matrix.pkg == 'dorm_framework' }}
        working-directory: ./${{ matrix.pkg }}
        run: dart run build_runner build test

      - name: Analyze project source
        working-directory: ./${{ matrix.pkg }}
        run: dart analyze

      - name: Configure dorm_meta
        run: dart pub get --directory dorm_meta

      - name: Prepare packages for publishing
        run: dart run dorm_meta/lib/dorm_meta.dart -i ${{ matrix.pkg }}

      - name: Publish to pub.dev
        uses: k-paxian/dart-package-publisher@v1.6
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          relativePath: ${{ matrix.pkg }}
          flutter: true
          skipTests: true
          suppressBuildRunner: true

  publish-children:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        pkg: [dorm_generator, dorm_firebase_database, dorm_bloc_database]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2

      - name: Install dependencies
        working-directory: ./${{ matrix.pkg }}
        run: dart pub get

      - name: Configure dorm_meta
        run: dart pub get --directory dorm_meta

      - name: Prepare packages for publishing
        run: dart run dorm_meta/lib/dorm_meta.dart -i ${{ matrix.pkg }} --pubspec-dependencies-values

      - name: Dart and Flutter Package Publisher
        uses: k-paxian/dart-package-publisher@v1.6
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          relativePath: ${{ matrix.pkg }}
          flutter: true
          skipTests: true
          suppressBuildRunner: true
