// dORM
// Copyright (C) 2023  Beet Software
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

/// Describes one part of a model's primary key.
sealed class IdSpec {
  /// Creates an [IdSpec].
  const IdSpec();
}

/// Describes a primary-key field generated by dORM.
///
/// The generated field is not required to exist in the annotated abstract
/// class. [as] is its Dart property name, [name] is its storage name, and
/// [type] is its Dart type.
final class GeneratedIdSpec extends IdSpec {
  /// Dart property name of the generated field.
  final Symbol as;

  /// Storage name of the generated field.
  final String name;

  /// Dart type of the generated field.
  final Type type;

  /// Creates a generated primary-key specification.
  const GeneratedIdSpec({
    this.as = #id,
    this.name = 'id',
    this.type = String,
  });
}

/// Describes a primary-key field already declared by the annotated class.
///
/// The generator resolves the field's Dart type and storage name from the
/// field referenced by [referTo].
final class ExistingIdSpec extends IdSpec {
  /// Name of the getter that declares the primary-key field.
  final Symbol referTo;

  /// Creates an existing-field primary-key specification.
  const ExistingIdSpec({required this.referTo});
}
