name: dorm_firebase_database
description: A dORM's Reference implementation using firebase_database. 
version: 0.3.0
publish_to: none

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  http: ^0.13.4
  firebase_auth: ^4.2.3
  firebase_core: ^2.4.0
  firebase_database: ^10.0.8
  dorm:
    git:
      url: https://github.com/enzo-santos/dorm.git
      ref: main
      path: dorm

dev_dependencies:
  lints: ^2.0.0
