name: dorm_firebase_database
version: 1.0.0-alpha.5
description: A firebase_database database engine for dORM.
homepage: https://github.com/beet-software/dorm/tree/main/dorm_firebase_database
repository: https://github.com/beet-software/dorm.git
environment:
  sdk: '>=3.0.5 <4.0.0'
false_secrets:
  - example/lib/main.dart

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_database: ^11.2.0
  dorm_framework: ^1.0.0-alpha.3
  rxdart: ^0.28.0
dev_dependencies:
  lints: ^5.0.0

dependency_overrides:
  dorm_framework:
    path: ../dorm_framework
