name: dorm_firebase_database
description: A dORM's Reference implementation using firebase_database. 
version: 0.1.0

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  firebase_database: ^9.0.17
  dorm_annotations:
    git:
      url: http://github.com/enzo-santos/dorm.git
      ref: main
      path: dorm_annotations

dev_dependencies:
  lints: ^2.0.0
