name: dorm_firebase_database
version: 1.0.0-alpha.3
description: A firebase_database database engine for dORM.
homepage: https://github.com/beet-software/dorm/tree/main/dorm_firebase_database
repository: https://github.com/beet-software/dorm.git
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  http: ^0.13.5
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  firebase_database: ^10.1.0
  dorm_framework:
    git:
      url: https://github.com/beet-software/dorm.git
      ref: main
      path: dorm_framework
dev_dependencies:
  lints: ^2.0.1
dependency_overrides:
  dorm_framework:
    path: ../dorm_framework
